### ISSUE TITLE
Correct the contact details in the footer on all pages

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#12]
The contact details on the home page footer are different from the contact details on other pages like the blog page or the book cover page. Please correct all contacts on all pages to the following details:

The first email address is info@scribehouse.ug
The alternative email is scribehouse.ug@gmail.com
The correct phone numbers to put are +256 (0)781 915759 and +256 (0)705 522273
The address is Kaddu Road, Kisaasi, Kampala.

**Comment by billionsjoel** [comment]
<img src="https://media4.giphy.com/media/QhmboW0R7eUbm/giphy.gif"/>
