### ISSUE TITLE
Change statement on the homepage

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#13]
Change the statement **_Scribe House is recommended by hundreds upon hundreds of authors_** to **Scribe House is recommended by many authors.** Be mindful of correct spellings,
![What people say Website](https://user-images.githubusercontent.com/89142192/203526166-1c8af680-ecde-4252-bf4c-f6cb3a9cc4b7.JPG)
 please.
![What people say Website](https://user-images.githubusercontent.com/89142192/203525764-5289edc7-e9dc-45e1-8da4-2d58d13f13e1.JPG)**

**Comment by billionsjoel** [comment]
<img src="https://media4.giphy.com/media/QhmboW0R7eUbm/giphy.gif"/>

**Comment by Crystal-BRB** [comment]
Lol! The GIF, HAHA!
