### ISSUE TITLE
Add our social media links in the footer

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#14]
The spaces for links to our social media sites are blank circles. Please fill them in. The facebook link, instagram and twitter.

**Comment by Crystal-BRB** [comment]
FACEBOOK LINK:
https://www.facebook.com/scribehouse.ug?mibextid=ZbWKwL

TWITTER LINK:
https://twitter.com/scribehouseUg?t=-obrnZPtooTl8bQ3qSPiKg&s=09 

INSTAGRAM LINK:
https://www.instagram.com/invites/contact/?i=47c6iqcb3hxl&utm_content=3gyudoj

**Comment by billionsjoel** [comment]
hi @Crystal-BRB ,

Done, please check for review.
