### ISSUE TITLE
Correct the arrangement of the Staff Photos

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#15]
1. Crystal 
_editor | writer | trainer_
Publishing Director

2. Carole
_writer | editor_
Administrative Director

3. Faith
_editor | digital marketer_
Production Manager

5. Jane 
Administrative Assistant

6. Joseph (PhD)
_researcher | writer_
Academic Publishing Consultant

7. Patricia Liz
Writer | Associate Editor | Poetry Editor 

8. Hassan
Writer | Associate Editor

9. Ssebo Lule
Poetry Editor

10. Henry
_Founder, ArmUp Media_
Book Design Partner

11. Correen
_Illustrator | Founder, KempihArt_
Book Design Partner

**Comment by billionsjoel** [comment]
Completed 👍
