### ISSUE TITLE
Add Ssebo Lule's photo 

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#16]
Add Ssebo Lule's photo to the lineup of the team.

![Ray 2 20210911_140343](https://user-images.githubusercontent.com/89142192/203582773-a823c14c-f4e1-4bf4-8073-a8f5683dc1d9.jpg)
![Ray 4 20210911_141504 (1)](https://user-images.githubusercontent.com/89142192/203582902-2d65c2ba-aaf0-4b83-b857-a641be1f03d6.jpg)

**Comment by billionsjoel** [comment]
<img src="https://media0.giphy.com/media/UtEUhkfriklonVdweC/giphy.gif"/>
