### ISSUE TITLE
change the covers on the home page

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#18]
The covers on the home page only show the book spines. Please replace with the following covers attached so we can see the front of each cover. You can include the words below each title in the text box.
1. His Grace
The autobiography of Bishop Henry Luke Orombi.

3. Say No to Fear
Learn to overcome five of our most common fears.

5. Emonevate
A poetry collection that will move you from an emotional rollercoaster to faith in God.

7. Truck Driver
A creative non-fictional story of the life of an East African truck driver.

![Orombi Mockup](https://user-images.githubusercontent.com/89142192/203611340-0638db89-7edf-44c7-ab3b-d35cc6d2c22b.jpg)

![SayNoToFear Mockup](https://user-images.githubusercontent.com/89142192/203611903-6f545c6b-b7b6-4fd8-978c-2d2fc0fe2eb6.jpg)

<img width="540" alt="Emonevate Mockup" src="https://user-images.githubusercontent.com/89142192/203612175-b5f2f017-c2b2-4f93-98da-53a6a3ef1066.png">

<img width="540" alt="Truck Driver Mockup" src="https://user-images.githubusercontent.com/89142192/203612291-7e67fa07-a80c-4120-abb3-67a8af9c8721.png">

![Home page covers](https://user-images.githubusercontent.com/89142192/203612468-f140c7af-ae6d-43ed-986a-990bbb28ea68.JPG)

**Comment by billionsjoel** [comment]
<img src="https://media4.giphy.com/media/ka56VEA01B9KDj3PZG/giphy.gif"/>
