### ISSUE TITLE
Remove 'buy book'

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#19]
Remove **_'buy book'_** from the covers on the home page because we are looking into a separate app that will sell the books.

![Home page covers](https://user-images.githubusercontent.com/89142192/203613184-df12ba76-0848-408f-bacf-f9b9469c43e4.JPG)

**Comment by billionsjoel** [comment]
Hi @Crystal-BRB ,

I think then we should add a link to where they can purchase the book from. i could even be a link to the authors social handle or email address.

**Comment by Crystal-BRB** [comment]
Alright, that's a great idea. I'll find the details and add them but after you've changed the covers being displayed.
