### ISSUE TITLE
VERY IMPORTANT: - Change wording on the home page

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#21]
Change the statement
 **What do you want to achieve? Start with a goal get a plan, and set targets for that goal. SCRIBE HOUSE focuses on helping you achieve your desired goal.**

Change to: 
**_'In the beginning was the Word...'_**

**![home page wording](https://user-images.githubusercontent.com/89142192/203616930-22ba9fc9-0d37-4f2f-82ce-b3ac30902697.JPG)**

**Comment by billionsjoel** [comment]
Done.

<img src="https://media4.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif"/>
