### ISSUE TITLE
I'm failing to add content to the website and can't edit existing content 

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#22]
I'm failing to add book covers. When adding, the notification says it's published but it's not showing on the website. I'm failing to edit the book cover content too. See the image attached, that's what pops up when I try to change the book cover images. 

![IMG_20221123_225414](https://user-images.githubusercontent.com/89142192/203642418-1f4b250a-58dd-42fc-b0f8-17dd29f2f051.jpg)

**Comment by billionsjoel** [comment]
Hi @Crystal-BRB,

I have tested everything about this and it works perfectly. Kindly try again or schedule a call for a demo. 

Thank you

**Comment by Crystal-BRB** [comment]
When I try to change the image, it re-directs and brings a page where I can't upload a different image. I'm trying to change the images of the first book cover posts, and I'm also trying to post new covers, but the option for adding images doesn't pop up.

![Book Cover Error](https://user-images.githubusercontent.com/89142192/207022453-cf424363-a555-426d-a9ff-9736241d2d47.JPG)



![SH BookCover Errors](https://user-images.githubusercontent.com/89142192/207022463-4547f699-2099-4544-ad6b-a63d020b1fc6.JPG)

**Comment by billionsjoel** [comment]
Alright, i now understand your issue, as i look into it. Kindly delete the whole book cover and re-upload it. That is a short way of changing the picture as i look to resolve the issue.

**Comment by Crystal-BRB** [comment]
Book covers can be added successfully after I first delete them, thank you. However I saw the other fields you added (publisher, cover by) but when I fill them in and publish, they don't show on the website.

**Comment by Crystal-BRB** [comment]
So this and the footer on the phone are the remaining issues. Thank you so much! The progress is great and the website is look much better.

**Comment by billionsjoel** [comment]
Please test this functionality. You can now update and edit bookcovers.
