### ISSUE TITLE
Correct blog dates on the home page

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#23]
Please correct the dates that appear on the blog on the home page.

![Blog Dates Errors](https://user-images.githubusercontent.com/89142192/207024675-3e0b2c28-5fd5-4a17-8b17-9c3cfe26bbbc.JPG)

**Comment by billionsjoel** [comment]
<img src="https://media2.giphy.com/media/UtEUhkfriklonVdweC/giphy.gif"/>
