### ISSUE TITLE
Correct the spelling of intereste

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#24]
For the book covers on the home page, the correct spelling is 'interested', not intrested.

![Screenshot_20221219_171616](https://user-images.githubusercontent.com/89142192/208451669-7d128f91-ae15-4eb1-b30e-e93cf3429116.jpg)

**Comment by billionsjoel** [comment]
<img src="https://media0.giphy.com/media/pdSncNyYgaH0wqaCqp/giphy.gif"/>
