### ISSUE TITLE
Some book cover fields aren't showing on the website

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#37]
The new fields 'cover by' and 'published by' aren't showing on the website. I can now edit and the new covers uploaded show, but those two new fields are still not showing.

![Bk Cover Fields](https://user-images.githubusercontent.com/89142192/219851623-4a2f72fa-0c2a-4077-b07b-e03fa86ae680.JPG)

**Comment by billionsjoel** [comment]
Thank you for the issue, let me work around the clock to fix that.

**Comment by billionsjoel** [comment]
Hi @Crystal-BRB ,

This issue has been fixed.
