### ISSUE TITLE
Add the autoreply function to the email app

### ISSUE THREAD

**Issue by Crystal-BRB** [billionsjoel/sh-app#9]
Is it possible to add the autoreply function to the email app on webmail, so that, for example if someone goes on leave, they can leave an automatic response email. Also, please look into increasing the space for our emails. We may need to know any associated costs in advance so that we can prepare the money.

**Comment by billionsjoel** [comment]
Hello @Crystal-BRB, this is possible. can you send me the message you would love me to set as an auto response to emails and after how long should the auto responder kick in ?

**Comment by billionsjoel** [comment]
<img src="https://media1.giphy.com/media/py2UYwTIX5SXm/giphy.gif"/>
